# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-node-browsers

      - image: minio/minio:RELEASE.2018-11-06T01-01-02Z
        command: server /data
        environment:
          MINIO_ACCESS_KEY: ONLY_ON_CIRCLE
          MINIO_SECRET_KEY: CAN_WE_DO_THIS
        ports: 9000:9000

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt"}}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - run:
          name: check types
          command: |
            . venv/bin/activate
            # pin mypy to avoid surprises
            pip install mypy==0.660
            # NOTE: We can add in stubs for modules we're using
            # BONUS: Tornado 6 will include types
            mypy bookstore --ignore-missing-imports

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: package up bookstore
          command: |
            . venv/bin/activate
            # Package up the package
            python setup.py sdist bdist_wheel

      - run:
          name: create virtual environment for packaged release
          command: |
            python3 -m venv venv_packaged_integration
            . venv_packaged_integration/bin/activate
            pip install --upgrade pip setuptools wheel
            pip install -U --force-reinstall dist/bookstore*.whl

      - run:
          name: integration tests
          command: |
            . venv_packaged_integration/bin/activate
            # Install the dependencies for our integration tester
            npm i
            node ci/integration.js

      - run:
          name: python tests
          command: |
            . venv/bin/activate
            pytest
